"""Dual-run pipeline for run_spark_merge_serverless_dag (generated by bh-migrate).

Topology:
  ensure_dualrun_clones
    >> [trigger_source_dag, trigger_migrated_dag]
    >> compare_dualrun_outputs

Clone and compare run on Databricks (notebook_task). Triggers may target Dataproc DAGs.
"""

from __future__ import annotations

from datetime import datetime, timedelta

from airflow import DAG
from airflow.operators.trigger_dagrun import TriggerDagRunOperator
from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator

DATABRICKS_CONN_ID = "databricks_default"
CLUSTER_ID = "{{ var.value.databricks_cluster_id }}"

default_args = {
    "owner": "data-platform",
    "depends_on_past": False,
    "retries": 0,
    "retry_delay": timedelta(minutes=5),
}

SOURCE_DAG_CONF = {
    "dual_run": {
        "mode": "source",
        "clone_index": 1,
        "main_class": "com.example.merge.Main",
        "group_id": "com.example.merge.Main:ec0b623191bf",
        "project_id": "9e030c69-a5d4-49a8-9560-bc6b7c7a4383",
        "target_overrides": {
            "target-table": "`databricks-migrate-activity`.schema1.customer_events_dual_clone_1"
        }
    },
    "target-table": "`databricks-migrate-activity`.schema1.customer_events_dual_clone_1",
    "target_table": "`databricks-migrate-activity`.schema1.customer_events_dual_clone_1"
}
MIGRATED_DAG_CONF = {
    "dual_run": {
        "mode": "migrated",
        "clone_index": 2,
        "main_class": "com.example.merge.Main",
        "group_id": "com.example.merge.Main:ec0b623191bf",
        "project_id": "9e030c69-a5d4-49a8-9560-bc6b7c7a4383",
        "target_overrides": {
            "target-table": "databricks-migrate-activity.schema1.customer_events_dual_clone_2"
        }
    },
    "target-table": "databricks-migrate-activity.schema1.customer_events_dual_clone_2",
    "target_table": "databricks-migrate-activity.schema1.customer_events_dual_clone_2"
}


def _cluster_notebook_payload(notebook_path: str, base_parameters: dict | None = None) -> dict:
    task: dict = {
        "notebook_path": notebook_path,
    }
    if base_parameters:
        task["base_parameters"] = base_parameters
    return {
        "existing_cluster_id": CLUSTER_ID,
        "notebook_task": task,
    }


with DAG(
    dag_id="dual_run_pipeline_run_spark_merge_serverless_dag",
    default_args=default_args,
    description="Dual-run validation for run_spark_merge_serverless_dag (com.example.merge.Main)",
    schedule=None,
    start_date=datetime(2024, 1, 1),
    catchup=False,
    tags=["dual-run", "bh-migrate", "run_spark_merge_serverless_dag"],
) as dag:
    ensure_dualrun_clones = DatabricksSubmitRunOperator(
        task_id="ensure_dualrun_clones",
        databricks_conn_id=DATABRICKS_CONN_ID,
        json=_cluster_notebook_payload("dbfs:/Volumes/databricks-migrate-activity/schema1/dualrun/run_spark_merge_serverless_dag/ensure_clones.py"),
    )

    trigger_source_dag = TriggerDagRunOperator(
        task_id="trigger_source_dag",
        trigger_dag_id="run_spark_merge_serverless_dag",
        conf=SOURCE_DAG_CONF,
        wait_for_completion=True,
    )

    trigger_migrated_dag = TriggerDagRunOperator(
        task_id="trigger_migrated_dag",
        trigger_dag_id="migrated_run_spark_merge_serverless_dag",
        conf=MIGRATED_DAG_CONF,
        wait_for_completion=True,
    )

    compare_dualrun_outputs = DatabricksSubmitRunOperator(
        task_id="compare_dualrun_outputs",
        databricks_conn_id=DATABRICKS_CONN_ID,
        json=_cluster_notebook_payload(
            "dbfs:/Volumes/databricks-migrate-activity/schema1/dualrun/run_spark_merge_serverless_dag/compare_outputs.py",
            {'dual_run_id': '{{ params.dual_run_id }}', 'project_name': '{{ params.project_name }}', 'report_root': 'dbfs:/tmp/dual_run'},
        ),
    )

    ensure_dualrun_clones >> [trigger_source_dag, trigger_migrated_dag]
    [trigger_source_dag, trigger_migrated_dag] >> compare_dualrun_outputs
