#!/usr/bin/env python3
# Dual-run compare (generated by bh-migrate)

COMPARE_PAIRS = [{'left_ref': 'databricks-migrate-activity.schema1.customer_events_dual_clone_1', 'right_ref': 'databricks-migrate-activity.schema1.customer_events_dual_clone_2', 'label': 'customer_events'}]
COMPARE_CONFIG = {'enabled': True, 'report': {'root_uri': 'gs://migration-dualrun/reports', 'summary_json': True, 'summary_markdown': True, 'summary_html': False, 'detail_format': 'delta', 'write_audit_tables': True, 'audit_catalog': 'migration_audit', 'audit_schema': 'dualrun'}, 'row_details': {'enabled': True, 'max_issue_rows_per_table': None, 'max_sample_rows_in_summary': 100, 'include_full_row_json': True, 'include_column_diff_json': True, 'include_mismatch_columns': True, 'max_json_length': 100000}, 'comparison_rules': {'fail_on_duplicate_keys': True, 'ignored_columns': ['_commit_timestamp', '_commit_version', '_change_type', '_change_ordinal', 'run_id', 'load_ts', 'updated_at'], 'sensitive_columns': [], 'numeric_tolerances': {}, 'timestamp_tolerance_seconds': 0}, 'checks': {'enable_basic_stats': True, 'enable_null_stats': True, 'enable_distinct_stats': True, 'enable_numeric_stats': True, 'enable_datetime_stats': True, 'enable_distribution_stats': True, 'enable_row_comparison': True, 'enable_delta_operation_metrics': True, 'enable_delta_version_stats': True, 'enable_distribution_by_status': False}, 'filters': {'business_date': None, 'where_clause': None}, 'runtime': {'fail_process_on': ['FAIL', 'BLOCKED']}, 'numeric_columns': None}
DEFAULT_REPORT_ROOT = 'gs://migration-dualrun/reports'

import argparse
import json

from pyspark.sql import SparkSession
from pyspark.sql import functions as F

parser = argparse.ArgumentParser(description='Execute dual-run output comparison')
parser.add_argument('--dual-run-id', required=True)
parser.add_argument('--candidate-id', required=True)
parser.add_argument('--project-name', required=True)
parser.add_argument('--report-root', default=DEFAULT_REPORT_ROOT)
args = parser.parse_args()

spark = SparkSession.builder.appName(f'dual-run-compare-{args.dual_run_id}').getOrCreate()
dual_run_id = args.dual_run_id
report_root = (
    f"{args.report_root.rstrip('/')}/project={args.project_name}"
    f"/candidate={args.candidate_id}/dual_run_id={dual_run_id}"
)
compare_results = {}

# --- Pair: customer_events ---
label = 'customer_events'
left_expr = 'databricks-migrate-activity.schema1.customer_events_dual_clone_1'
right_expr = 'databricks-migrate-activity.schema1.customer_events_dual_clone_2'
where_sql = ''
left_df = spark.sql(f"SELECT * FROM {left_expr}{where_sql}")
right_df = spark.sql(f"SELECT * FROM {right_expr}{where_sql}")
left_count = left_df.count()
right_count = right_df.count()

# Pair customer_events — basic.row_count
row_delta = right_count - left_count
compare_results['customer_events:basic.row_count'] = {
    'check_id': 'basic.row_count',
    'pair_label': 'customer_events',
    'severity': 'FAIL' if row_delta != 0 else 'PASS',
    'metrics': {
        'left_count': left_count,
        'right_count': right_count,
        'delta': row_delta,
        'delta_pct': (row_delta / left_count) if left_count else 0.0,
    },
}

# Pair customer_events — basic.column_count
left_schema_rows = spark.sql('DESCRIBE TABLE databricks-migrate-activity.schema1.customer_events_dual_clone_1').collect()
right_schema_rows = spark.sql('DESCRIBE TABLE databricks-migrate-activity.schema1.customer_events_dual_clone_2').collect()
left_cols = [r.col_name for r in left_schema_rows if r.col_name and not str(r.col_name).startswith('#')]
right_cols = [r.col_name for r in right_schema_rows if r.col_name and not str(r.col_name).startswith('#')]
col_delta = len(right_cols) - len(left_cols)
compare_results['customer_events:basic.column_count'] = {
    'check_id': 'basic.column_count',
    'pair_label': 'customer_events',
    'severity': 'FAIL' if col_delta != 0 else 'PASS',
    'metrics': {
        'left_columns': len(left_cols),
        'right_columns': len(right_cols),
        'delta': col_delta,
    },
}

# Pair customer_events — basic.schema_equality
schema_match = left_schema_rows == right_schema_rows
compare_results['customer_events:basic.schema_equality'] = {
    'check_id': 'basic.schema_equality',
    'pair_label': 'customer_events',
    'severity': 'FAIL' if not schema_match else 'PASS',
    'metrics': {
        'schema_match': schema_match,
        'missing_columns_in_right': sorted(set(left_cols) - set(right_cols)),
        'extra_columns_in_right': sorted(set(right_cols) - set(left_cols)),
        'order_mismatches': left_cols != right_cols,
    },
}

# Pair customer_events — basic.partition_columns
try:
    _lp = spark.sql('DESCRIBE DETAIL databricks-migrate-activity.schema1.customer_events_dual_clone_1').select('partitionColumns').first()[0]
    _rp = spark.sql('DESCRIBE DETAIL databricks-migrate-activity.schema1.customer_events_dual_clone_2').select('partitionColumns').first()[0]
    left_partitions = list(_lp or [])
    right_partitions = list(_rp or [])
    partition_match = left_partitions == right_partitions
    compare_results['customer_events:basic.partition_columns'] = {
        'check_id': 'basic.partition_columns',
        'pair_label': 'customer_events',
        'severity': 'WARN' if partition_match is False else 'PASS',
        'metrics': {
            'left_partitions': left_partitions,
            'right_partitions': right_partitions,
            'partition_match': partition_match,
        },
    }
except Exception as _exc:
    compare_results['customer_events:basic.partition_columns'] = {
        'check_id': 'basic.partition_columns',
        'pair_label': 'customer_events',
        'severity': 'BLOCKED',
        'message': str(_exc),
        'metrics': {},
    }

# Pair customer_events — null stats
null_columns = sorted(set(left_df.columns) & set(right_df.columns))
null_count_metrics = {}
null_pct_metrics = {}
for _col in null_columns:
    _ln = left_df.select(F.sum(F.col(_col).isNull().cast('int')).alias('c')).first()[0] or 0
    _rn = right_df.select(F.sum(F.col(_col).isNull().cast('int')).alias('c')).first()[0] or 0
    null_count_metrics[_col] = {'left_nulls': int(_ln), 'right_nulls': int(_rn), 'delta': int(_rn) - int(_ln)}
    null_pct_metrics[_col] = {
        'left_null_pct': float(_ln) / left_count if left_count else 0.0,
        'right_null_pct': float(_rn) / right_count if right_count else 0.0,
        'delta_pct': (float(_rn) / right_count if right_count else 0.0) - (float(_ln) / left_count if left_count else 0.0),
    }
newly_introduced_null_columns = [c for c in null_columns if null_count_metrics[c]['right_nulls'] > null_count_metrics[c]['left_nulls']]

compare_results['customer_events:nulls.count_per_column'] = {
    'check_id': 'nulls.count_per_column',
    'pair_label': 'customer_events',
    'severity': 'REVIEW' if any(v['delta'] != 0 for v in null_count_metrics.values()) else 'PASS',
    'metrics': {'columns': null_count_metrics},
}

compare_results['customer_events:nulls.percentage_per_column'] = {
    'check_id': 'nulls.percentage_per_column',
    'pair_label': 'customer_events',
    'severity': 'REVIEW' if any(v['delta_pct'] != 0 for v in null_pct_metrics.values()) else 'PASS',
    'metrics': {'columns': null_pct_metrics},
}

compare_results['customer_events:nulls.newly_introduced'] = {
    'check_id': 'nulls.newly_introduced',
    'pair_label': 'customer_events',
    'severity': 'REVIEW' if newly_introduced_null_columns else 'PASS',
    'metrics': {'newly_introduced_null_columns': newly_introduced_null_columns},
}

# Pair customer_events — distinct.column_counts
distinct_columns = sorted(set(left_df.columns) & set(right_df.columns))
distinct_metrics = {}
for _col in distinct_columns:
    _ld = left_df.select(_col).distinct().count()
    _rd = right_df.select(_col).distinct().count()
    distinct_metrics[_col] = {'left_distinct': _ld, 'right_distinct': _rd, 'delta': _rd - _ld}
compare_results['customer_events:distinct.column_counts'] = {
    'check_id': 'distinct.column_counts',
    'pair_label': 'customer_events',
    'severity': 'REVIEW' if any(v['delta'] != 0 for v in distinct_metrics.values()) else 'PASS',
    'metrics': {'columns': distinct_metrics},
}

# Pair customer_events — keys.distinct_key_count (blocked)
compare_results['customer_events:keys.distinct_key_count'] = {
    'check_id': 'keys.distinct_key_count',
    'pair_label': 'customer_events',
    'severity': 'BLOCKED',
    'message': 'key_columns not provided',
    'metrics': {},
}

# Pair customer_events — keys.duplicate_count (blocked)
compare_results['customer_events:keys.duplicate_count'] = {
    'check_id': 'keys.duplicate_count',
    'pair_label': 'customer_events',
    'severity': 'BLOCKED',
    'message': 'key_columns not provided',
    'metrics': {},
}

# Pair customer_events — numeric.aggregates (blocked)
compare_results['customer_events:numeric.aggregates'] = {
    'check_id': 'numeric.aggregates',
    'pair_label': 'customer_events',
    'severity': 'BLOCKED',
    'message': 'numeric_columns not provided',
    'metrics': {},
}

# Pair customer_events — datetime.range (blocked)
compare_results['customer_events:datetime.range'] = {
    'check_id': 'datetime.range',
    'pair_label': 'customer_events',
    'severity': 'BLOCKED',
    'message': 'no date/timestamp columns configured',
    'metrics': {},
}

# Pair customer_events — datetime.count_by_date (blocked)
compare_results['customer_events:datetime.count_by_date'] = {
    'check_id': 'datetime.count_by_date',
    'pair_label': 'customer_events',
    'severity': 'BLOCKED',
    'message': 'date_columns not provided',
    'metrics': {},
}

# Pair customer_events — distribution.by_partition (blocked)
compare_results['customer_events:distribution.by_partition'] = {
    'check_id': 'distribution.by_partition',
    'pair_label': 'customer_events',
    'severity': 'BLOCKED',
    'message': 'partition_columns not provided',
    'metrics': {},
}

# Pair customer_events — distribution.by_status (skipped)
compare_results['customer_events:distribution.by_status'] = {
    'check_id': 'distribution.by_status',
    'pair_label': 'customer_events',
    'severity': 'SKIPPED',
    'message': 'enable_distribution_by_status is False',
    'metrics': {},
}

# Pair customer_events — rows.hash_based
comparable_cols = sorted(set(left_df.columns) & set(right_df.columns))
left_hashes = left_df.select(F.sha2(F.concat_ws('||', *[F.col(c).cast('string') for c in comparable_cols]), 256).alias('row_hash')).groupBy('row_hash').count()
right_hashes = right_df.select(F.sha2(F.concat_ws('||', *[F.col(c).cast('string') for c in comparable_cols]), 256).alias('row_hash')).groupBy('row_hash').count()
hash_join = left_hashes.alias('l').join(right_hashes.alias('r'), on='row_hash', how='full_outer')
hash_only_left = hash_join.filter(F.col('l.row_hash').isNotNull() & F.col('r.row_hash').isNull()).count()
hash_only_right = hash_join.filter(F.col('l.row_hash').isNull() & F.col('r.row_hash').isNotNull()).count()
hash_count_mismatch = hash_join.filter(
    F.col('l.row_hash').isNotNull() & F.col('r.row_hash').isNotNull() & (F.col('l.count') != F.col('r.count'))
).count()
hash_in_both = hash_join.filter(
    F.col('l.row_hash').isNotNull() & F.col('r.row_hash').isNotNull() & (F.col('l.count') == F.col('r.count'))
).count()
hash_only_left_df = hash_join.filter(F.col('l.row_hash').isNotNull() & F.col('r.row_hash').isNull()).select('l.row_hash', 'l.count')
hash_only_right_df = hash_join.filter(F.col('l.row_hash').isNull() & F.col('r.row_hash').isNotNull()).select('r.row_hash', 'r.count')
_hol_path = f'{report_root}/tables/{label}/row_issues/hash_only_left'
_hor_path = f'{report_root}/tables/{label}/row_issues/hash_only_right'
hash_only_left_df.write.mode("overwrite").format("delta").save(_hol_path)
hash_only_right_df.write.mode("overwrite").format("delta").save(_hor_path)
hash_severity = 'PASS'
if hash_only_left or hash_only_right or hash_count_mismatch:
    hash_severity = 'FAIL'
compare_results['customer_events:rows.hash_based'] = {
    'check_id': 'rows.hash_based',
    'pair_label': 'customer_events',
    'severity': hash_severity,
    'metrics': {
        'hash_in_both': hash_in_both,
        'hash_only_left': hash_only_left,
        'hash_only_right': hash_only_right,
        'hash_count_mismatch': hash_count_mismatch,
    },
}

# Pair customer_events — delta_ops.metrics
left_history = spark.sql('DESCRIBE HISTORY databricks-migrate-activity.schema1.customer_events_dual_clone_1 LIMIT 5').collect()
right_history = spark.sql('DESCRIBE HISTORY databricks-migrate-activity.schema1.customer_events_dual_clone_2 LIMIT 5').collect()
left_operations = [r.operation for r in left_history]
right_operations = [r.operation for r in right_history]
def _parse_metrics(row):
    raw = getattr(row, 'operationMetrics', None) or {}
    if isinstance(raw, str):
        try:
            raw = json.loads(raw)
        except Exception:
            raw = {}
    return raw
_metric_keys = ['numTargetRowsInserted', 'numTargetRowsUpdated', 'numTargetRowsDeleted']
_lm = _parse_metrics(left_history[0]) if left_history else {}
_rm = _parse_metrics(right_history[0]) if right_history else {}
metrics_block = {}
for _k in _metric_keys:
    _lv = int(_lm.get(_k, 0) or 0)
    _rv = int(_rm.get(_k, 0) or 0)
    metrics_block[_k] = {'left': _lv, 'right': _rv, 'match': _lv == _rv}
inserted_match = metrics_block.get('numTargetRowsInserted', {}).get('match', True)
updated_match = metrics_block.get('numTargetRowsUpdated', {}).get('match', True)
deleted_match = metrics_block.get('numTargetRowsDeleted', {}).get('match', True)
delta_ops_severity = 'PASS'
if inserted_match is False or updated_match is False or deleted_match is False:
    delta_ops_severity = 'FAIL'
compare_results['customer_events:delta_ops.metrics'] = {
    'check_id': 'delta_ops.metrics',
    'pair_label': 'customer_events',
    'severity': delta_ops_severity,
    'metrics': {
        'left_operations': left_operations,
        'right_operations': right_operations,
        'metrics': metrics_block,
        'inserted_match': inserted_match,
        'updated_match': updated_match,
        'deleted_match': deleted_match,
    },
}

# Pair customer_events — delta_version.stats
left_history = spark.sql('DESCRIBE HISTORY databricks-migrate-activity.schema1.customer_events_dual_clone_1 LIMIT 100').collect()
right_history = spark.sql('DESCRIBE HISTORY databricks-migrate-activity.schema1.customer_events_dual_clone_2 LIMIT 100').collect()
left_versions = [int(r.version) for r in left_history]
right_versions = [int(r.version) for r in right_history]
left_sequence = [r.operation for r in left_history]
right_sequence = [r.operation for r in right_history]
sequence_match = left_sequence == right_sequence
commit_count_match = len(left_history) == len(right_history)
delta_version_severity = 'PASS'
if sequence_match is False:
    delta_version_severity = 'FAIL'
elif commit_count_match is False:
    delta_version_severity = 'REVIEW'
compare_results['customer_events:delta_version.stats'] = {
    'check_id': 'delta_version.stats',
    'pair_label': 'customer_events',
    'severity': delta_version_severity,
    'metrics': {
        'left_start_version': min(left_versions) if left_versions else None,
        'right_start_version': min(right_versions) if right_versions else None,
        'left_end_version': max(left_versions) if left_versions else None,
        'right_end_version': max(right_versions) if right_versions else None,
        'left_commits': len(left_history),
        'right_commits': len(right_history),
        'left_sequence': left_sequence,
        'right_sequence': right_sequence,
        'sequence_match': sequence_match,
        'commit_count_match': commit_count_match,
    },
}

# --- summary ---
_severity_order = {'PASS': 0, 'SKIPPED': 0, 'WARN': 1, 'REVIEW': 2, 'BLOCKED': 3, 'FAIL': 4}
overall_severity = 'PASS'
for _entry in compare_results.values():
    _sev = _entry.get('severity', 'PASS')
    if _severity_order.get(_sev, 0) > _severity_order.get(overall_severity, 0):
        overall_severity = _sev

summary = {
    'dual_run_id': dual_run_id,
    'candidate_id': args.candidate_id,
    'project_name': args.project_name,
    'report_root': report_root,
    'overall_severity': overall_severity,
    'results': compare_results,
}
summary_json = json.dumps(summary, default=str)
summary_path = f'{report_root}/summary/summary.json'
try:
    dbutils.fs.put(summary_path, summary_json, overwrite=True)  # type: ignore[name-defined]
except Exception:
    spark.sparkContext.parallelize([summary_json]).coalesce(1).write.mode('overwrite').text(summary_path)

fail_on = ['FAIL', 'BLOCKED']
if overall_severity in fail_on:
    raise SystemExit(1)

