# Databricks notebook source

# COMMAND ----------
# Dual-run clone setup (generated by bh-migrate)

# COMMAND ----------
# Resolve storage location for `databricks-migrate-activity`.schema1.customer_events
source_loc = spark.sql('DESCRIBE DETAIL `databricks-migrate-activity`.schema1.customer_events').select('location').first()[0]
parent = source_loc.rstrip('/').rsplit('/', 1)[0]
resolved_clone_locations = {
    1: f"{parent}/customer_events_dual_clone_1",
    2: f"{parent}/customer_events_dual_clone_2",
}

# COMMAND ----------
# Clone `databricks-migrate-activity`.schema1.customer_events_dual_clone_1
if not spark.catalog.tableExists("`databricks-migrate-activity`.schema1.customer_events_dual_clone_1"):
    spark.sql(
    f"CREATE TABLE IF NOT EXISTS `databricks-migrate-activity`.schema1.customer_events_dual_clone_1\n"
    f"DEEP CLONE `databricks-migrate-activity`.schema1.customer_events\n"
    f"LOCATION '{resolved_clone_locations[1]}'"
)

# COMMAND ----------
# Clone `databricks-migrate-activity`.schema1.customer_events_dual_clone_2
if not spark.catalog.tableExists("`databricks-migrate-activity`.schema1.customer_events_dual_clone_2"):
    spark.sql(
    f"CREATE TABLE IF NOT EXISTS `databricks-migrate-activity`.schema1.customer_events_dual_clone_2\n"
    f"DEEP CLONE `databricks-migrate-activity`.schema1.customer_events\n"
    f"LOCATION '{resolved_clone_locations[2]}'"
)
