"""Dual-run pipeline for test_spark_merge_serverless_dag (generated by bh-migrate).

Topology:
  ensure_dualrun_clones
    >> [trigger_source_dag, trigger_migrated_dag]
    >> compare_dualrun_outputs
"""

from __future__ import annotations

from datetime import datetime, timedelta

from airflow import DAG
from airflow.operators.trigger_dagrun import TriggerDagRunOperator
from airflow.providers.google.cloud.operators.dataproc import DataprocSubmitJobOperator

GCP_PROJECT_ID = "{{ var.value.gcp_project_id }}"
GCP_REGION = "{{ var.value.gcp_region }}"
DATAPROC_CLUSTER_NAME = "{{ var.value.dataproc_cluster_name }}"

default_args = {
    "owner": "data-platform",
    "depends_on_past": False,
    "retries": 0,
    "retry_delay": timedelta(minutes=5),
}

SOURCE_DAG_CONF = {
    "dual_run": {
        "mode": "source",
        "clone_index": 1,
        "main_class": "com.example.merge.Main",
        "group_id": "com.example.merge.Main:97f8bbd025f5",
        "project_id": "6603ecb0-2bf4-4845-9395-b02b532bb8a6",
        "target_overrides": {
            "target-table": "databricks-migrate-activity.schema1.customer_events_dual_clone_1"
        }
    },
    "target-table": "databricks-migrate-activity.schema1.customer_events_dual_clone_1",
    "target_table": "databricks-migrate-activity.schema1.customer_events_dual_clone_1"
}
MIGRATED_DAG_CONF = {
    "dual_run": {
        "mode": "migrated",
        "clone_index": 2,
        "main_class": "com.example.merge.Main",
        "group_id": "com.example.merge.Main:97f8bbd025f5",
        "project_id": "6603ecb0-2bf4-4845-9395-b02b532bb8a6",
        "target_overrides": {
            "target-table": "databricks-migrate-activity.schema1.customer_events_dual_clone_2"
        }
    },
    "target-table": "databricks-migrate-activity.schema1.customer_events_dual_clone_2",
    "target_table": "databricks-migrate-activity.schema1.customer_events_dual_clone_2"
}

with DAG(
    dag_id="dual_run_pipeline_test_spark_merge_serverless_dag",
    default_args=default_args,
    description="Dual-run validation for test_spark_merge_serverless_dag (com.example.merge.Main)",
    schedule=None,
    start_date=datetime(2024, 1, 1),
    catchup=False,
    tags=["dual-run", "bh-migrate", "test_spark_merge_serverless_dag"],
) as dag:
    ensure_dualrun_clones = DataprocSubmitJobOperator(
        task_id="ensure_dualrun_clones",
        project_id=GCP_PROJECT_ID,
        region=GCP_REGION,
        job={
            "reference": {"project_id": GCP_PROJECT_ID},
            "placement": {"cluster_name": DATAPROC_CLUSTER_NAME},
            "pyspark_job": {
                "main_python_file_uri": "notebooks/dualrun/ensure_clones.py",
            },
        },
    )

    trigger_source_dag = TriggerDagRunOperator(
        task_id="trigger_source_dag",
        trigger_dag_id="test_spark_merge_serverless_dag",
        conf=SOURCE_DAG_CONF,
        wait_for_completion=True,
    )

    trigger_migrated_dag = TriggerDagRunOperator(
        task_id="trigger_migrated_dag",
        trigger_dag_id="migrated_test_spark_merge_serverless_dag",
        conf=MIGRATED_DAG_CONF,
        wait_for_completion=True,
    )

    compare_dualrun_outputs = DataprocSubmitJobOperator(
        task_id="compare_dualrun_outputs",
        project_id=GCP_PROJECT_ID,
        region=GCP_REGION,
        job={
            "reference": {"project_id": GCP_PROJECT_ID},
            "placement": {"cluster_name": DATAPROC_CLUSTER_NAME},
            "pyspark_job": {
                "main_python_file_uri": "notebooks/dualrun/compare_outputs.py",
                "args": ["--results-path", "dbfs:/tmp/dual_run/compare_results.json"],
            },
        },
    )

    ensure_dualrun_clones >> [trigger_source_dag, trigger_migrated_dag]
    [trigger_source_dag, trigger_migrated_dag] >> compare_dualrun_outputs
