"""Dual-run pipeline for test_spark_merge_serverless_dag (generated by bh-migrate).

Trigger-based topology with Databricks serverless notebook compare, matching the
source DAG compute model.
"""

from __future__ import annotations

from datetime import datetime, timedelta

from airflow import DAG
from airflow.operators.trigger_dagrun import TriggerDagRunOperator
from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator

DATABRICKS_CONN_ID = "databricks_default"

default_args = {
    "owner": "data-platform",
    "depends_on_past": False,
    "retries": 0,
    "retry_delay": timedelta(minutes=5),
}

SOURCE_DAG_CONF = {
    "dual_run": {
        "mode": "source",
        "clone_index": 1,
        "main_class": "com.example.merge.Main",
        "group_id": "com.example.merge.Main:97f8bbd025f5",
        "project_id": "workspace-migration",
        "target_overrides": {
            "target-table": "`databricks-migrate-activity`.schema1.customer_events_dual_clone_1"
        }
    },
    "target-table": "`databricks-migrate-activity`.schema1.customer_events_dual_clone_1",
    "target_table": "`databricks-migrate-activity`.schema1.customer_events_dual_clone_1"
}
MIGRATED_DAG_CONF = {
    "dual_run": {
        "mode": "migrated",
        "clone_index": 2,
        "main_class": "com.example.merge.Main",
        "group_id": "com.example.merge.Main:97f8bbd025f5",
        "project_id": "workspace-migration",
        "target_overrides": {
            "target-table": "databricks-migrate-activity.schema1.customer_events_dual_clone_2"
        }
    },
    "target-table": "databricks-migrate-activity.schema1.customer_events_dual_clone_2",
    "target_table": "databricks-migrate-activity.schema1.customer_events_dual_clone_2"
}


def _serverless_notebook_task(
    task_key: str,
    notebook_path: str,
    base_parameters: dict,
) -> dict:
    notebook_task: dict = {
        "notebook_path": notebook_path,
        "base_parameters": base_parameters,
    }
    if notebook_path.startswith("/Workspace/"):
        notebook_task["source"] = "WORKSPACE"
    return {
        "run_name": task_key,
        "tasks": [
            {
                "task_key": task_key,
                "environment_key": "default",
                "notebook_task": notebook_task,
            }
        ],
        "environments": [
            {
                "environment_key": "default",
                "spec": {"environment_version": "4"},
            }
        ],
    }


with DAG(
    dag_id="dual_run_pipeline_test_spark_merge_serverless_dag",
    default_args=default_args,
    description="Dual-run validation for test_spark_merge_serverless_dag (com.example.merge.Main)",
    schedule=None,
    start_date=datetime(2024, 1, 1),
    catchup=False,
    tags=["dual-run", "bh-migrate", "test_spark_merge_serverless_dag"],
) as dag:
    ensure_dualrun_clones = DatabricksSubmitRunOperator(
        task_id="ensure_dualrun_clones",
        databricks_conn_id=DATABRICKS_CONN_ID,
        json=_serverless_notebook_task("ensure_clones", "/Workspace/Users/rohit@bighammer.ai/dualrun/test_spark_merge_serverless_dag/ensure_clones.py", {}),
    )

    trigger_source_dag = TriggerDagRunOperator(
        task_id="trigger_source_dag",
        trigger_dag_id="test_spark_merge_serverless_dag",
        conf=SOURCE_DAG_CONF,
        wait_for_completion=True,
    )

    trigger_migrated_dag = TriggerDagRunOperator(
        task_id="trigger_migrated_dag",
        trigger_dag_id="migrated_test_spark_merge_serverless_dag",
        conf=MIGRATED_DAG_CONF,
        wait_for_completion=True,
    )

    compare_dualrun_outputs = DatabricksSubmitRunOperator(
        task_id="compare_dualrun_outputs",
        databricks_conn_id=DATABRICKS_CONN_ID,
        json=_serverless_notebook_task(
            "compare_outputs",
            "/Workspace/Users/rohit@bighammer.ai/dualrun/test_spark_merge_serverless_dag/compare_outputs.py",
            {'dual_run_id': "{{ (dag_run.conf or {}).get('dual_run_id', dag_run.run_id) }}", 'project_name': "{{ (dag_run.conf or {}).get('project_name', dag.dag_id) }}", 'report_root': 'dbfs:/tmp/dual_run'},
        ),
    )

    ensure_dualrun_clones >> [trigger_source_dag, trigger_migrated_dag]
    [trigger_source_dag, trigger_migrated_dag] >> compare_dualrun_outputs
