"""Dual-run pipeline for test_spark_merge_serverless_dag (generated by bh-migrate).

Trigger-based topology with Databricks serverless notebook compare, matching the
source DAG compute model.
"""

from __future__ import annotations

from datetime import datetime, timedelta

from airflow import DAG
from airflow.providers.databricks.operators.databricks import DatabricksSubmitRunOperator

DATABRICKS_CONN_ID = "databricks_default"
# Patched at deploy time by build-deploy-dags (DATABRICKS_WORKSPACE_BASE GitHub var).
DATABRICKS_WORKSPACE_BASE = "/Volumes/databricks-migrate-activity/schema1/dualrun"

default_args = {
    "owner": "data-platform",
    "depends_on_past": False,
    "retries": 0,
    "retry_delay": timedelta(minutes=5),
}

from airflow.models.param import Param
from airflow.operators.python import PythonOperator

SOURCE_DAG_CONF = {}
MIGRATED_DAG_CONF = {}
DAG_PARAMS = {
    "project_name": Param(default="", type="string"),
    "catalog": Param(default="databricks-migrate-activity", type="string"),
    "clone_suffix": Param(default="_dual_clone_", type="string"),
    "input-path": Param(default="databricks-8259550742932689-unitycatalog/8259550742932689/incoming/customer_events_merge.csv", type="string"),
    "merge-key": Param(default="id", type="string"),
    "target-table": Param(default="databricks-migrate-activity.schema1.customer_events", type="string"),
}


def _resolve_branch_conf(branch: str, default: dict, **context):
    dag_run = context.get("dag_run")
    conf = (dag_run.conf if dag_run else None) or {}
    key = "source_branch_conf" if branch == "source" else "migrated_branch_conf"
    override = conf.get(key)
    if isinstance(override, dict):
        return override
    merged = dict(default)
    params = context.get("params") or {}
    for name, value in params.items():
        if name in (
            "project_name",
            "catalog",
            "clone_suffix",
            "compare_pairs_json",
        ) or str(name).startswith("compare_left_ref_") or str(name).startswith("compare_right_ref_"):
            continue
        if isinstance(value, (str, int, float, bool)):
            merged[name] = value
            underscored = str(name).replace("-", "_")
            if underscored != name:
                merged[underscored] = value
    return merged


def _trigger_child_dag(target_dag_id: str, branch: str, default_conf: dict, wait: bool, **context):
    from airflow.api.common.trigger_dag import trigger_dag

    conf = _resolve_branch_conf(branch, default_conf, **context)
    trigger_dag(
        dag_id=target_dag_id,
        run_conf=conf,
        wait_for_completion=wait,
        replace_microseconds=False,
    )


def _serverless_notebook_task(
    task_key: str,
    notebook_path: str,
    base_parameters: dict,
) -> dict:
    notebook_task: dict = {
        "notebook_path": notebook_path,
        "base_parameters": base_parameters,
    }
    if notebook_path.startswith("/Workspace/"):
        notebook_task["source"] = "WORKSPACE"
    return {
        "run_name": task_key,
        "tasks": [
            {
                "task_key": task_key,
                "environment_key": "default",
                "notebook_task": notebook_task,
            }
        ],
        "environments": [
            {
                "environment_key": "default",
                "spec": {"environment_version": "4"},
            }
        ],
    }


with DAG(
    dag_id="dual_run_pipeline_test_spark_merge_serverless_dag",
    default_args=default_args,
    description="Dual-run validation for test_spark_merge_serverless_dag (com.example.merge.Main)",
    schedule=None,
    start_date=datetime(2024, 1, 1),
    catchup=False,
    tags=["dual-run", "bh-migrate", "test_spark_merge_serverless_dag"],
    params=DAG_PARAMS,
) as dag:
    ensure_dualrun_clones = DatabricksSubmitRunOperator(
        task_id="ensure_dualrun_clones",
        databricks_conn_id=DATABRICKS_CONN_ID,
        json=_serverless_notebook_task(
            "ensure_clones",
            f"{DATABRICKS_WORKSPACE_BASE}/test_spark_merge_serverless_dag/ensure_clones.py",
            {'clone_plan_json': "{{ (dag_run.conf or {}).get('clone_plan_json', '{}') }}", 'clone_suffix': '{{ (dag_run.conf or {}).get("clone_suffix") or params.get("clone_suffix", "_dual_clone_") }}', 'catalog': '{{ (dag_run.conf or {}).get("catalog") or params.get("catalog", "databricks-migrate-activity") }}', 'input-path': '{{ (dag_run.conf or {}).get("input-path") or params.get("input-path", "") }}', 'merge-key': '{{ (dag_run.conf or {}).get("merge-key") or params.get("merge-key", "") }}', 'target-table': '{{ (dag_run.conf or {}).get("target-table") or params.get("target-table", "") }}'},
        ),
    )

    trigger_source_dag = PythonOperator(
        task_id="trigger_source_dag",
        python_callable=_trigger_child_dag,
        op_kwargs={
            "target_dag_id": "test_spark_merge_serverless_dag",
            "branch": "source",
            "default_conf": SOURCE_DAG_CONF,
            "wait": True,
        },
    )

    trigger_migrated_dag = PythonOperator(
        task_id="trigger_migrated_dag",
        python_callable=_trigger_child_dag,
        op_kwargs={
            "target_dag_id": "migrated_test_spark_merge_serverless_dag",
            "branch": "migrated",
            "default_conf": MIGRATED_DAG_CONF,
            "wait": True,
        },
    )

    compare_dualrun_outputs = DatabricksSubmitRunOperator(
        task_id="compare_dualrun_outputs",
        databricks_conn_id=DATABRICKS_CONN_ID,
        json=_serverless_notebook_task(
            "compare_outputs",
            f"{DATABRICKS_WORKSPACE_BASE}/test_spark_merge_serverless_dag/compare_outputs.py",
            {'dual_run_id': "{{ (dag_run.conf or {}).get('dual_run_id', dag_run.run_id) }}", 'project_name': "{{ (dag_run.conf or {}).get('project_name', dag.dag_id) }}", 'report_root': 'gs://{{ var.value.dual_run_bucket }}/dual_run/reports', 'compare_pairs_json': '{{ (dag_run.conf or {}).get("compare_pairs_json") or params.get("compare_pairs_json", "[{\\"left_ref\\":\\"databricks-migrate-activity.schema1.customer_events_dual_clone_1\\",\\"right_ref\\":\\"databricks-migrate-activity.schema1.customer_events_dual_clone_2\\",\\"label\\":\\"customer_events\\"}]") }}', 'compare_left_ref_0': '{{ (dag_run.conf or {}).get("compare_left_ref_0") or params.get("compare_left_ref_0", "databricks-migrate-activity.schema1.customer_events_dual_clone_1") }}', 'compare_right_ref_0': '{{ (dag_run.conf or {}).get("compare_right_ref_0") or params.get("compare_right_ref_0", "databricks-migrate-activity.schema1.customer_events_dual_clone_2") }}'},
        ),
    )

    ensure_dualrun_clones >> [trigger_source_dag, trigger_migrated_dag]
    [trigger_source_dag, trigger_migrated_dag] >> compare_dualrun_outputs
