# Databricks notebook source

# COMMAND ----------
"""Runtime dual-run clone setup (generated by bh-migrate)."""

from __future__ import annotations

import json

from pyspark.sql import SparkSession

spark = SparkSession.builder.getOrCreate()


def _load_plan_json() -> dict:
    import os
    raw = os.environ.get("clone_plan_json", "{}")
    if not raw or raw == "{}":
        try:
            from pyspark.dbutils import DBUtils
            raw = DBUtils().widgets.get("clone_plan_json")
        except Exception:
            pass
    return json.loads(raw or "{}")


def _exists(fqn: str) -> bool:
    try:
        return spark.catalog.tableExists(fqn)
    except Exception:
        return False


plan_data = _load_plan_json()
for cell in plan_data.get("preamble_cells") or []:
    exec(cell, {"spark": spark, "json": json})

for clone_item in plan_data.get("clones") or []:
    target = clone_item.get("target") or {}
    fqn = target.get("fqn", "")
    stmt_sql = clone_item.get("sql", "")
    skip = clone_item.get("skip_if_exists", True)
    if skip and fqn and _exists(fqn):
        print(f"skip existing clone: {fqn}")
        continue
    if "{resolved_clone_locations[" in stmt_sql:
        index = int(target.get("index") or 1)
        source = target.get("source") or {}
        catalog = (source.get("catalog") or "").strip("`")
        schema = (source.get("source_schema") or "").strip("`")
        table_name = source.get("table_name") or ""
        source_ref = f"`{catalog}`.{schema}.{table_name}" if catalog else source.get("ref", "")
        target_ref = f"`{catalog}`.{schema}.{fqn.rsplit('.', 1)[-1]}" if catalog and "." in fqn else fqn
        location = resolved_clone_locations[index]
        spark.sql(
            f"CREATE TABLE IF NOT EXISTS {target_ref}\n"
            f"DEEP CLONE {source_ref}\n"
            f"LOCATION '{location}'"
        )
    else:
        spark.sql(stmt_sql)
    print(f"clone ready: {fqn}")

print(json.dumps({"status": "ok", "clone_count": len(plan_data.get("clones") or [])}))
