# Databricks notebook source

# COMMAND ----------
"""Runtime mock source writer (generated by bh-migrate)."""

from __future__ import annotations

import json
import os

from pyspark.sql import SparkSession
from pyspark.sql import types as T

spark = SparkSession.builder.getOrCreate()


def _widget(name: str, default: str = "") -> str:
    try:
        from pyspark.dbutils import DBUtils
        raw = DBUtils().widgets.get(name)
        if raw is not None and str(raw).strip():
            return str(raw).strip()
    except Exception:
        pass
    return str(os.environ.get(name, default) or default).strip()


def _load_specs() -> list:
    raw = _widget("source_specs_json", "[]")
    if not raw:
        raw = "[]"
    try:
        parsed = json.loads(raw)
        if not isinstance(parsed, list):
            raise ValueError("source_specs_json must be a JSON array")
        return parsed
    except json.JSONDecodeError as exc:
        raise ValueError(f"invalid source_specs_json: {exc}") from exc


def _load_mock_config() -> dict:
    raw = _widget("mock_config", "{}")
    try:
        parsed = json.loads(raw or "{}")
        return parsed if isinstance(parsed, dict) else {}
    except json.JSONDecodeError:
        return {}


def _use_mock_source() -> bool:
    flag = _widget("use_mock_source", "false").lower()
    return flag in ("true", "1", "yes")


def _spark_type(dtype: str):
    mapping = {
        "string": T.StringType(),
        "bigint": T.LongType(),
        "long": T.LongType(),
        "int": T.IntegerType(),
        "integer": T.IntegerType(),
        "double": T.DoubleType(),
        "float": T.FloatType(),
        "boolean": T.BooleanType(),
        "timestamp": T.TimestampType(),
        "date": T.DateType(),
    }
    return mapping.get(str(dtype or "string").lower(), T.StringType())


def _columns_from_schema(schema) -> list:
    return [{"name": f.name, "type": f.dataType.simpleString()} for f in schema.fields]


from datetime import date, datetime, timedelta

def build_column_hints(
    columns: list[dict[str, Any]],
    sample_rows: list[dict[str, Any]] | None,
) -> dict[str, dict[str, Any]]:
    """Derive per-column statistics from sample rows (no raw values stored)."""
    hints: dict[str, dict[str, Any]] = {}
    if not sample_rows:
        return hints

    for col in columns:
        name = str(col.get("name") or "col")
        dtype = _normalize_dtype(col.get("type"))
        values = [row.get(name) for row in sample_rows if name in row and row[name] is not None]
        if not values:
            continue

        hint: dict[str, Any] = {"dtype": dtype}

        if dtype in _INT_TYPES:
            nums = [_coerce_int(v) for v in values]
            nums = [n for n in nums if n is not None]
            if nums:
                hint["min"] = min(nums)
                hint["max"] = max(nums)
        elif dtype in _FLOAT_TYPES:
            nums = [_coerce_float(v) for v in values]
            nums = [n for n in nums if n is not None]
            if nums:
                hint["min"] = min(nums)
                hint["max"] = max(nums)
        elif dtype in _BOOL_TYPES:
            bools = [bool(v) for v in values]
            hint["true_ratio"] = sum(1 for b in bools if b) / len(bools)
        elif dtype in _DATE_TYPES:
            dates = [_parse_date(v) for v in values]
            dates = [d for d in dates if d is not None]
            if dates:
                hint["min_date"] = min(dates).isoformat()
                hint["max_date"] = max(dates).isoformat()
        elif dtype in _TIMESTAMP_TYPES:
            stamps = [_parse_datetime(v) for v in values]
            stamps = [s for s in stamps if s is not None]
            if stamps:
                hint["min_ts"] = min(stamps).isoformat(sep=" ")
                hint["max_ts"] = max(stamps).isoformat(sep=" ")
        else:
            lengths = [len(str(v)) for v in values]
            hint["avg_length"] = sum(lengths) // len(lengths) if lengths else 8
            hint["max_length"] = max(lengths) if lengths else 32

        hints[name] = hint
    return hints

def synthetic_value(
    column: dict[str, Any],
    row_index: int,
    hints: dict[str, dict[str, Any]] | None = None,
) -> Any:
    """Generate one synthetic cell value; never copies sample row values."""
    name = str(column.get("name") or "col")
    dtype = _normalize_dtype(column.get("type"))
    hint = (hints or {}).get(name) or {}

    if dtype in _INT_TYPES:
        min_v = hint.get("min")
        max_v = hint.get("max")
        if min_v is not None and max_v is not None:
            span = int(max_v) - int(min_v)
            if span > 0:
                return int(min_v) + (row_index % (span + 1))
            return int(min_v) + row_index
        return row_index

    if dtype in _FLOAT_TYPES:
        min_v = hint.get("min")
        max_v = hint.get("max")
        if min_v is not None and max_v is not None and float(max_v) != float(min_v):
            span = float(max_v) - float(min_v)
            step = span / max(span, 1.0)
            return round(float(min_v) + (row_index % 1000) * step / 1000.0, 6)
        return float(row_index)

    if dtype in _BOOL_TYPES:
        ratio = hint.get("true_ratio")
        if ratio is not None:
            return (row_index % 100) < int(float(ratio) * 100)
        return row_index % 2 == 0

    if dtype in _DATE_TYPES:
        min_d = _parse_date(hint.get("min_date"))
        max_d = _parse_date(hint.get("max_date"))
        if min_d and max_d:
            span = (max_d - min_d).days
            offset = row_index % (span + 1) if span >= 0 else row_index % 3650
            return (min_d + timedelta(days=offset)).isoformat()
        return (date(2020, 1, 1) + timedelta(days=row_index % 3650)).isoformat()

    if dtype in _TIMESTAMP_TYPES:
        min_ts = _parse_datetime(hint.get("min_ts"))
        max_ts = _parse_datetime(hint.get("max_ts"))
        if min_ts and max_ts:
            span_hours = int((max_ts - min_ts).total_seconds() // 3600)
            offset = row_index % (span_hours + 1) if span_hours >= 0 else row_index
            return (min_ts + timedelta(hours=offset)).isoformat(sep=" ")
        return (datetime(2020, 1, 1) + timedelta(hours=row_index)).isoformat(sep=" ")

    if not hint:
        return f"mock_{name}_{row_index}"

    avg_len = int(hint.get("avg_length") or 8)
    max_len = int(hint.get("max_length") or 32)
    length = min(max(avg_len, 4), max_len)
    suffix = f"{row_index:0{min(length, 12)}d}"[-length:]
    return f"mock_{name}_{suffix}"

def generate_mock_rows(
    columns: list[dict[str, Any]],
    row_count: int,
    *,
    column_hints: dict[str, dict[str, Any]] | None = None,
) -> list[dict[str, Any]]:
    """Build row_count synthetic rows using column definitions and optional hints."""
    rows: list[dict[str, Any]] = []
    for i in range(row_count):
        rows.append(
            {
                str(col.get("name") or "col"): synthetic_value(col, i, column_hints)
                for col in columns
            }
        )
    return rows



def _analyze_source(spec: dict, sample_size: int) -> tuple[list, dict]:
    source = str(spec.get("source") or "").strip()
    kind = str(spec.get("kind") or "").lower()
    fmt = str(spec.get("format") or "csv").lower()
    columns = list(spec.get("columns") or [])
    column_hints_map = dict(spec.get("column_hints") or {})
    sample_rows: list = []

    if source:
        try:
            if kind == "delta_table":
                df = spark.table(source)
                if not columns:
                    columns = _columns_from_schema(df.schema)
                sample_rows = [r.asDict() for r in df.limit(sample_size).collect()]
            else:
                reader = spark.read
                if fmt == "csv":
                    reader = reader.option("header", True)
                elif fmt == "tsv":
                    reader = reader.option("header", True).option("sep", "\t")
                df = reader.format(fmt if fmt not in ("txt",) else "csv").load(source)
                if not columns:
                    columns = _columns_from_schema(df.schema)
                sample_rows = [r.asDict() for r in df.limit(sample_size).collect()]
            if sample_rows:
                column_hints_map = build_column_hints(columns, sample_rows)
        except Exception as exc:
            print(f"source analysis skipped for {spec.get('parameter')}: {exc}")

    if not columns:
        columns = [{"name": "mock_id", "type": "bigint"}, {"name": "mock_value", "type": "string"}]
    return columns, column_hints_map


def _build_dataframe(spec: dict, mock_config: dict) -> "DataFrame":
    row_count = int(spec.get("row_count") or mock_config.get("mock_row_count") or 1000)
    sample_size = int(mock_config.get("sample_size") or 100)

    columns, column_hints_map = _analyze_source(spec, sample_size)
    rows = generate_mock_rows(columns, row_count, column_hints=column_hints_map)

    schema = T.StructType([T.StructField(c["name"], _spark_type(c.get("type"))) for c in columns])
    return spark.createDataFrame(rows, schema=schema)


def _write_spec(spec: dict, mock_config: dict) -> None:
    parameter = spec.get("parameter") or "unknown"
    mock_destination = str(spec.get("mock_destination") or "").strip()
    if not mock_destination:
        raise ValueError(f"mock_destination missing for parameter {parameter!r}")

    fmt = str(spec.get("format") or "csv").lower()
    kind = str(spec.get("kind") or "").lower()
    row_count = int(spec.get("row_count") or mock_config.get("mock_row_count") or 1000)

    df = _build_dataframe(spec, mock_config)

    if kind == "delta_table":
        df.write.mode("overwrite").format("delta").saveAsTable(mock_destination)
    elif fmt == "parquet":
        df.write.mode("overwrite").parquet(mock_destination)
    elif fmt == "json":
        df.write.mode("overwrite").json(mock_destination)
    elif fmt == "avro":
        df.write.mode("overwrite").format("avro").save(mock_destination)
    elif fmt == "tsv":
        df.write.mode("overwrite").option("header", True).option("sep", "\t").csv(mock_destination)
    else:
        df.write.mode("overwrite").option("header", True).csv(mock_destination)

    print(f"wrote mock data for {parameter} to {mock_destination} ({fmt}, {row_count} rows)")


use_mock = _use_mock_source()
specs = _load_specs()
mock_config = _load_mock_config()

if use_mock and not specs:
    raise ValueError("use_mock_source is true but source_specs_json is empty")

processed = 0
for spec in specs:
    if not spec.get("mock_enabled", True):
        continue
    parameter = spec.get("parameter") or "unknown"
    try:
        _write_spec(spec, mock_config)
        processed += 1
    except Exception as exc:
        raise RuntimeError(f"mock failed for parameter {parameter!r}: {exc}") from exc

print(json.dumps({"status": "ok", "spec_count": len(specs), "processed": processed, "use_mock_source": use_mock}))
