# Databricks notebook source

# COMMAND ----------
"""Runtime mock source writer (generated by bh-migrate)."""

from __future__ import annotations

import json
import os

from pyspark.sql import SparkSession
from pyspark.sql import types as T

spark = SparkSession.builder.getOrCreate()


def _widget(name: str, default: str = "") -> str:
    try:
        from pyspark.dbutils import DBUtils
        raw = DBUtils().widgets.get(name)
        if raw is not None and str(raw).strip():
            return str(raw).strip()
    except Exception:
        pass
    return str(os.environ.get(name, default) or default).strip()


def _load_specs() -> list:
    raw = _widget("source_specs_json", "[]")
    if not raw:
        raw = "[]"
    try:
        parsed = json.loads(raw)
        if not isinstance(parsed, list):
            raise ValueError("source_specs_json must be a JSON array")
        return parsed
    except json.JSONDecodeError as exc:
        raise ValueError(f"invalid source_specs_json: {exc}") from exc


def _load_mock_config() -> dict:
    raw = _widget("mock_config", "{}")
    try:
        parsed = json.loads(raw or "{}")
        return parsed if isinstance(parsed, dict) else {}
    except json.JSONDecodeError:
        return {}


def _use_mock_source() -> bool:
    flag = _widget("use_mock_source", "false").lower()
    return flag in ("true", "1", "yes")


def _spark_type(dtype: str, column: dict | None = None):
    if column and column.get("as_string"):
        return T.StringType()
    mapping = {
        "string": T.StringType(),
        "bigint": T.LongType(),
        "long": T.LongType(),
        "int": T.IntegerType(),
        "integer": T.IntegerType(),
        "double": T.DoubleType(),
        "float": T.FloatType(),
        "boolean": T.BooleanType(),
        "timestamp": T.TimestampType(),
        "date": T.DateType(),
    }
    return mapping.get(str(dtype or "string").lower(), T.StringType())


import re
from datetime import date, datetime, timedelta, timezone

PROMOTION_THRESHOLD = 0.8

_TEXT_FORMATS = frozenset({"csv", "tsv", "txt", "json"})

_EPOCH_S_MIN = 1_000_000_000  # ~2001
_EPOCH_S_MAX = 4_000_000_000  # ~2096
_EPOCH_MS_MIN = _EPOCH_S_MIN * 1000
_EPOCH_MS_MAX = _EPOCH_S_MAX * 1000


@dataclass(frozen=True)
class TemporalPattern:
    kind: str  # date | timestamp
    regex: re.Pattern[str]
    strptime: str
    output_format: str


_TEMPORAL_PATTERNS: tuple[TemporalPattern, ...] = (
    TemporalPattern(
        "timestamp",
        re.compile(r"^\d{4}-\d{2}-\d{2}[ T]\d{2}:\d{2}:\d{2}(?:\.\d+)?$"),
        "%Y-%m-%d %H:%M:%S",
        "%Y-%m-%d %H:%M:%S",
    ),
    TemporalPattern(
        "timestamp",
        re.compile(r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?$"),
        "%Y-%m-%dT%H:%M:%S",
        "%Y-%m-%dT%H:%M:%S",
    ),
    TemporalPattern(
        "date",
        re.compile(r"^\d{4}-\d{2}-\d{2}$"),
        "%Y-%m-%d",
        "%Y-%m-%d",
    ),
    TemporalPattern(
        "date",
        re.compile(r"^\d{2}-\d{2}-\d{4}$"),
        "%d-%m-%Y",
        "%d-%m-%Y",
    ),
    TemporalPattern(
        "date",
        re.compile(r"^\d{2}-\d{2}-\d{4}$"),
        "%m-%d-%Y",
        "%m-%d-%Y",
    ),
    TemporalPattern(
        "date",
        re.compile(r"^\d{2}/\d{2}/\d{4}$"),
        "%d/%m/%Y",
        "%d/%m/%Y",
    ),
    TemporalPattern(
        "date",
        re.compile(r"^\d{2}/\d{2}/\d{4}$"),
        "%m/%d/%Y",
        "%m/%d/%Y",
    ),
)

_INT_RE = re.compile(r"^-?\d+$")
_FLOAT_RE = re.compile(r"^-?\d+\.\d+$")


def _normalize_dtype(dtype: str | None) -> str:
    return str(dtype or "string").lower()


def _is_string_like(dtype: str) -> bool:
    return _normalize_dtype(dtype) in ("string", "varchar", "")


def _parse_with_format(text: str, fmt: str) -> date | datetime | None:
    try:
        if "H" in fmt or "T" in fmt:
            return datetime.strptime(text[:26], fmt)
        parsed = datetime.strptime(text[:10], fmt)
        return parsed.date()
    except ValueError:
        return None


def _valid_calendar(parsed: date | datetime) -> bool:
    value = parsed.date() if isinstance(parsed, datetime) else parsed
    return 1900 <= value.year <= 2100


def parse_temporal_value(value: Any) -> tuple[str, date | datetime, str] | None:
    """Return (kind, parsed_value, output_format) when value matches a temporal pattern."""
    if value is None:
        return None
    if isinstance(value, datetime):
        return "timestamp", value, "%Y-%m-%d %H:%M:%S"
    if isinstance(value, date):
        return "date", value, "%Y-%m-%d"
    text = str(value).strip()
    if not text:
        return None

    if _INT_RE.match(text):
        num = int(text)
        if _EPOCH_MS_MIN <= num <= _EPOCH_MS_MAX:
            return "timestamp", datetime.fromtimestamp(num / 1000.0, tz=timezone.utc).replace(tzinfo=None), "epoch_ms"
        if _EPOCH_S_MIN <= num <= _EPOCH_S_MAX:
            return "timestamp", datetime.fromtimestamp(num, tz=timezone.utc).replace(tzinfo=None), "epoch_s"

    candidates: list[tuple[str, date | datetime, str, TemporalPattern]] = []
    for pattern in _TEMPORAL_PATTERNS:
        if not pattern.regex.match(text):
            continue
        parsed = _parse_with_format(text, pattern.strptime)
        if parsed is not None and _valid_calendar(parsed):
            candidates.append((pattern.kind, parsed, pattern.output_format, pattern))

    if not candidates:
        return None

    if len(candidates) == 1:
        kind, parsed, output_format, _ = candidates[0]
        return kind, parsed, output_format

    # Disambiguate DD-MM-YYYY vs MM-DD-YYYY by successful parse count.
    by_format: dict[str, tuple[str, date | datetime, str]] = {}
    for pattern in _TEMPORAL_PATTERNS:
        if not pattern.regex.match(text):
            continue
        parsed = _parse_with_format(text, pattern.strptime)
        if parsed is not None and _valid_calendar(parsed):
            by_format[pattern.strptime] = (pattern.kind, parsed, pattern.output_format)
    if by_format:
        _, best = max(by_format.items(), key=lambda item: item[0])
        return best
    kind, parsed, output_format, _ = candidates[0]
    return kind, parsed, output_format


def _score_pattern(values: list[Any], pattern: TemporalPattern) -> int:
    matched = 0
    for value in values:
        text = str(value).strip()
        if not text or not pattern.regex.match(text):
            continue
        parsed = _parse_with_format(text, pattern.strptime)
        if parsed is not None and _valid_calendar(parsed):
            matched += 1
    return matched


def _infer_temporal_column(values: list[Any]) -> dict[str, Any] | None:
    non_null = [v for v in values if v is not None and str(v).strip()]
    if not non_null:
        return None

    epoch_hits = sum(
        1
        for v in non_null
        if _INT_RE.match(str(v).strip())
        and (
            _EPOCH_MS_MIN <= int(str(v).strip()) <= _EPOCH_MS_MAX
            or _EPOCH_S_MIN <= int(str(v).strip()) <= _EPOCH_S_MAX
        )
    )
    if epoch_hits / len(non_null) >= PROMOTION_THRESHOLD:
        sample = int(str(non_null[0]).strip())
        if _EPOCH_MS_MIN <= sample <= _EPOCH_MS_MAX:
            return {"type": "timestamp", "output_format": "epoch_ms", "epoch_unit": "ms", "as_string": True}
        return {"type": "timestamp", "output_format": "epoch_s", "epoch_unit": "s", "as_string": True}

    best: TemporalPattern | None = None
    best_score = 0
    for pattern in _TEMPORAL_PATTERNS:
        score = _score_pattern(non_null, pattern)
        if score > best_score:
            best_score = score
            best = pattern
    if best is None or best_score / len(non_null) < PROMOTION_THRESHOLD:
        return None
    return {
        "type": best.kind,
        "output_format": best.output_format,
        "as_string": True,
    }


def _infer_numeric_column(values: list[Any]) -> dict[str, Any] | None:
    non_null = [v for v in values if v is not None and str(v).strip()]
    if not non_null:
        return None
    if all(_INT_RE.match(str(v).strip()) for v in non_null):
        return {"type": "bigint", "as_string": False}
    if all(_FLOAT_RE.match(str(v).strip()) or _INT_RE.match(str(v).strip()) for v in non_null):
        return {"type": "double", "as_string": False}
    return None


def infer_column_types(
    columns: list[dict[str, Any]],
    sample_rows: list[dict[str, Any]],
    fmt: str = "csv",
) -> list[dict[str, Any]]:
    """Promote string columns using sample-value regex inference for text file formats."""
    text_format = str(fmt or "csv").lower() in _TEXT_FORMATS
    inferred: list[dict[str, Any]] = []
    for col in columns:
        row = dict(col)
        name = str(row.get("name") or "col")
        dtype = _normalize_dtype(row.get("type"))
        values = [r.get(name) for r in sample_rows if name in r]

        if text_format and _is_string_like(dtype) and values:
            temporal = _infer_temporal_column(values)
            if temporal:
                row.update(temporal)
            else:
                numeric = _infer_numeric_column(values)
                if numeric:
                    row.update(numeric)
        inferred.append(row)
    return inferred


def format_temporal_output(value: date | datetime, output_format: str) -> str:
    if output_format == "epoch_ms":
        dt = value if isinstance(value, datetime) else datetime(value.year, value.month, value.day)
        return str(int(dt.replace(tzinfo=timezone.utc).timestamp() * 1000))
    if output_format == "epoch_s":
        dt = value if isinstance(value, datetime) else datetime(value.year, value.month, value.day)
        return str(int(dt.replace(tzinfo=timezone.utc).timestamp()))
    if isinstance(value, datetime):
        return value.strftime(output_format)
    return value.strftime(output_format)

_INT_TYPES = frozenset({"bigint", "long", "int", "integer"})
_FLOAT_TYPES = frozenset({"double", "float"})
_BOOL_TYPES = frozenset({"boolean", "bool"})
_DATE_TYPES = frozenset({"date"})
_TIMESTAMP_TYPES = frozenset({"timestamp"})


def _normalize_dtype(dtype: str | None) -> str:
    raw = str(dtype or "string").lower()
    if raw in ("epoch_s", "epoch_ms"):
        return "timestamp"
    return raw


def _coerce_float(value: Any) -> float | None:
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def _coerce_int(value: Any) -> int | None:
    try:
        return int(value)
    except (TypeError, ValueError):
        return None


def _parse_date(value: Any) -> date | None:
    if isinstance(value, date) and not isinstance(value, datetime):
        return value
    if isinstance(value, datetime):
        return value.date()
    parsed = parse_temporal_value(value)
    if parsed is None:
        return None
    kind, dt_value, _ = parsed
    if kind == "date":
        return dt_value if isinstance(dt_value, date) else dt_value.date()
    if kind == "timestamp" and isinstance(dt_value, datetime):
        return dt_value.date()
    return None


def _parse_datetime(value: Any) -> datetime | None:
    if isinstance(value, datetime):
        return value
    if isinstance(value, date):
        return datetime(value.year, value.month, value.day)
    parsed = parse_temporal_value(value)
    if parsed is None:
        return None
    _, dt_value, _ = parsed
    if isinstance(dt_value, datetime):
        return dt_value
    if isinstance(dt_value, date):
        return datetime(dt_value.year, dt_value.month, dt_value.day)
    return None


def build_column_hints(
    columns: list[dict[str, Any]],
    sample_rows: list[dict[str, Any]] | None,
) -> dict[str, dict[str, Any]]:
    """Derive per-column statistics from sample rows (no raw values stored)."""
    hints: dict[str, dict[str, Any]] = {}
    if not sample_rows:
        return hints

    for col in columns:
        name = str(col.get("name") or "col")
        dtype = _normalize_dtype(col.get("type"))
        values = [row.get(name) for row in sample_rows if name in row and row[name] is not None]
        if not values:
            continue

        hint: dict[str, Any] = {"dtype": dtype}
        if col.get("output_format"):
            hint["output_format"] = col["output_format"]
        if col.get("epoch_unit"):
            hint["epoch_unit"] = col["epoch_unit"]
        if col.get("as_string"):
            hint["as_string"] = bool(col["as_string"])

        if dtype in _INT_TYPES:
            nums = [_coerce_int(v) for v in values]
            nums = [n for n in nums if n is not None]
            if nums:
                hint["min"] = min(nums)
                hint["max"] = max(nums)
        elif dtype in _FLOAT_TYPES:
            nums = [_coerce_float(v) for v in values]
            nums = [n for n in nums if n is not None]
            if nums:
                hint["min"] = min(nums)
                hint["max"] = max(nums)
        elif dtype in _BOOL_TYPES:
            bools = [bool(v) for v in values]
            hint["true_ratio"] = sum(1 for b in bools if b) / len(bools)
        elif dtype in _DATE_TYPES:
            dates = [_parse_date(v) for v in values]
            dates = [d for d in dates if d is not None]
            if dates:
                hint["min_date"] = min(dates).isoformat()
                hint["max_date"] = max(dates).isoformat()
        elif dtype in _TIMESTAMP_TYPES:
            stamps = [_parse_datetime(v) for v in values]
            stamps = [s for s in stamps if s is not None]
            if stamps:
                hint["min_ts"] = min(stamps).isoformat(sep=" ")
                hint["max_ts"] = max(stamps).isoformat(sep=" ")
        else:
            lengths = [len(str(v)) for v in values]
            hint["avg_length"] = sum(lengths) // len(lengths) if lengths else 8
            hint["max_length"] = max(lengths) if lengths else 32

        hints[name] = hint
    return hints


def _format_synthetic_temporal(
    value: date | datetime,
    hint: dict[str, Any],
) -> Any:
    output_format = hint.get("output_format")
    if hint.get("as_string") and output_format:
        return format_temporal_output(value, str(output_format))
    if isinstance(value, datetime):
        return value
    return value


def synthetic_value(
    column: dict[str, Any],
    row_index: int,
    hints: dict[str, dict[str, Any]] | None = None,
) -> Any:
    """Generate one synthetic cell value; never copies sample row values."""
    name = str(column.get("name") or "col")
    dtype = _normalize_dtype(column.get("type"))
    hint = dict((hints or {}).get(name) or {})
    if column.get("output_format") and "output_format" not in hint:
        hint["output_format"] = column["output_format"]
    if column.get("as_string"):
        hint["as_string"] = True

    if dtype in _INT_TYPES:
        min_v = hint.get("min")
        max_v = hint.get("max")
        if min_v is not None and max_v is not None:
            span = int(max_v) - int(min_v)
            if span > 0:
                return int(min_v) + (row_index % (span + 1))
            return int(min_v) + row_index
        return row_index

    if dtype in _FLOAT_TYPES:
        min_v = hint.get("min")
        max_v = hint.get("max")
        if min_v is not None and max_v is not None and float(max_v) != float(min_v):
            span = float(max_v) - float(min_v)
            step = span / max(span, 1.0)
            return round(float(min_v) + (row_index % 1000) * step / 1000.0, 6)
        return float(row_index)

    if dtype in _BOOL_TYPES:
        ratio = hint.get("true_ratio")
        if ratio is not None:
            return (row_index % 100) < int(float(ratio) * 100)
        return row_index % 2 == 0

    if dtype in _DATE_TYPES:
        min_d = _parse_date(hint.get("min_date"))
        max_d = _parse_date(hint.get("max_date"))
        if min_d and max_d:
            span = (max_d - min_d).days
            offset = row_index % (span + 1) if span >= 0 else row_index % 3650
            generated = min_d + timedelta(days=offset)
            return _format_synthetic_temporal(generated, hint)
        generated = date(2020, 1, 1) + timedelta(days=row_index % 3650)
        return _format_synthetic_temporal(generated, hint)

    if dtype in _TIMESTAMP_TYPES:
        min_ts = _parse_datetime(hint.get("min_ts"))
        max_ts = _parse_datetime(hint.get("max_ts"))
        if min_ts and max_ts:
            span_hours = int((max_ts - min_ts).total_seconds() // 3600)
            offset = row_index % (span_hours + 1) if span_hours >= 0 else row_index
            generated = min_ts + timedelta(hours=offset)
            return _format_synthetic_temporal(generated, hint)
        generated = datetime(2020, 1, 1) + timedelta(hours=row_index)
        return _format_synthetic_temporal(generated, hint)

    if not hint:
        return f"mock_{name}_{row_index}"

    avg_len = int(hint.get("avg_length") or 8)
    max_len = int(hint.get("max_length") or 32)
    length = min(max(avg_len, 4), max_len)
    suffix = f"{row_index:0{min(length, 12)}d}"[-length:]
    return f"mock_{name}_{suffix}"


def generate_mock_rows(
    columns: list[dict[str, Any]],
    row_count: int,
    *,
    column_hints: dict[str, dict[str, Any]] | None = None,
) -> list[dict[str, Any]]:
    """Build row_count synthetic rows using column definitions and optional hints."""
    rows: list[dict[str, Any]] = []
    for i in range(row_count):
        rows.append(
            {
                str(col.get("name") or "col"): synthetic_value(col, i, column_hints)
                for col in columns
            }
        )
    return rows


def use_string_temporal_columns(columns: list[dict[str, Any]], fmt: str) -> bool:
    """True when text formats should keep temporal values as formatted strings."""
    return str(fmt or "csv").lower() in ("csv", "tsv", "txt", "json")


def coerce_rows_for_spark_schema(
    rows: list[dict[str, Any]],
    columns: list[dict[str, Any]],
    fmt: str,
) -> list[dict[str, Any]]:
    """Leave string temporal columns as strings for text file writes."""
    if not use_string_temporal_columns(columns, fmt):
        return rows
    coerced: list[dict[str, Any]] = []
    for row in rows:
        item = dict(row)
        for col in columns:
            if not col.get("as_string"):
                continue
            name = str(col.get("name") or "col")
            value = item.get(name)
            if isinstance(value, (date, datetime)):
                output_format = str(col.get("output_format") or "%Y-%m-%d")
                item[name] = format_temporal_output(value, output_format)
        coerced.append(item)
    return coerced

DEFAULT_PLACEHOLDER_COLUMNS = [
    {"name": "mock_id", "type": "bigint"},
    {"name": "mock_value", "type": "string"},
]


def is_placeholder_columns(columns: list[dict[str, Any]] | None) -> bool:
    if not columns or len(columns) != 2:
        return False
    names = {str(c.get("name")) for c in columns}
    return names == {"mock_id", "mock_value"}


def columns_from_spark_schema(schema: Any) -> list[dict[str, Any]]:
    return [{"name": f.name, "type": f.dataType.simpleString()} for f in schema.fields]


def read_source_dataframe(spark: Any, *, source: str, kind: str, fmt: str) -> Any:
    if kind == "delta_table":
        return spark.table(source)
    reader = spark.read
    normalized = str(fmt or "csv").lower()
    if normalized == "csv":
        reader = reader.option("header", True)
    elif normalized == "tsv":
        reader = reader.option("header", True).option("sep", "\t")
    spark_fmt = normalized if normalized not in ("txt",) else "csv"
    return reader.format(spark_fmt).load(source)


def analyze_mock_source(
    spec: dict[str, Any],
    *,
    sample_size: int,
    spark: Any,
) -> tuple[list[dict[str, Any]], dict[str, dict[str, Any]]]:
    """Read production source and return inferred columns + column hints."""
    source = str(spec.get("source") or "").strip()
    kind = str(spec.get("kind") or "").lower()
    fmt = str(spec.get("format") or "csv").lower()
    spec_columns = list(spec.get("columns") or [])
    column_hints_map = dict(spec.get("column_hints") or {})
    columns: list[dict[str, Any]] = []
    sample_rows: list[dict[str, Any]] = []

    if source:
        try:
            df = read_source_dataframe(spark, source=source, kind=kind, fmt=fmt)
            columns = columns_from_spark_schema(df.schema)
            sample_rows = [r.asDict() for r in df.limit(max(1, int(sample_size))).collect()]
            if sample_rows:
                columns = infer_column_types(columns, sample_rows, fmt)
                column_hints_map = build_column_hints(columns, sample_rows)
        except Exception as exc:
            print(f"source analysis skipped for {spec.get('parameter')}: {exc}")

    if not columns:
        if spec_columns and not is_placeholder_columns(spec_columns):
            columns = [dict(c) for c in spec_columns]
        else:
            columns = [dict(c) for c in DEFAULT_PLACEHOLDER_COLUMNS]

    return columns, column_hints_map


def _build_dataframe(spec: dict, mock_config: dict) -> "DataFrame":
    row_count = int(spec.get("row_count") or mock_config.get("mock_row_count") or 1000)
    sample_size = int(mock_config.get("sample_size") or 100)
    fmt = str(spec.get("format") or "csv").lower()

    columns, column_hints_map = analyze_mock_source(spec, sample_size=sample_size, spark=spark)
    rows = generate_mock_rows(columns, row_count, column_hints=column_hints_map)
    rows = coerce_rows_for_spark_schema(rows, columns, fmt)

    schema = T.StructType(
        [T.StructField(str(c["name"]), _spark_type(c.get("type"), c)) for c in columns]
    )
    return spark.createDataFrame(rows, schema=schema)


def _write_spec(spec: dict, mock_config: dict) -> None:
    parameter = spec.get("parameter") or "unknown"
    mock_destination = str(spec.get("mock_destination") or "").strip()
    if not mock_destination:
        raise ValueError(f"mock_destination missing for parameter {parameter!r}")

    fmt = str(spec.get("format") or "csv").lower()
    kind = str(spec.get("kind") or "").lower()
    row_count = int(spec.get("row_count") or mock_config.get("mock_row_count") or 1000)

    df = _build_dataframe(spec, mock_config)

    if kind == "delta_table":
        df.write.mode("overwrite").format("delta").saveAsTable(mock_destination)
    elif fmt == "parquet":
        df.write.mode("overwrite").parquet(mock_destination)
    elif fmt == "json":
        df.write.mode("overwrite").json(mock_destination)
    elif fmt == "avro":
        df.write.mode("overwrite").format("avro").save(mock_destination)
    elif fmt == "tsv":
        df.write.mode("overwrite").option("header", True).option("sep", "\t").csv(mock_destination)
    else:
        df.write.mode("overwrite").option("header", True).csv(mock_destination)

    print(f"wrote mock data for {parameter} to {mock_destination} ({fmt}, {row_count} rows)")


use_mock = _use_mock_source()
specs = _load_specs()
mock_config = _load_mock_config()

if use_mock and not specs:
    raise ValueError("use_mock_source is true but source_specs_json is empty")

processed = 0
for spec in specs:
    if not spec.get("mock_enabled", True):
        continue
    parameter = spec.get("parameter") or "unknown"
    try:
        _write_spec(spec, mock_config)
        processed += 1
    except Exception as exc:
        raise RuntimeError(f"mock failed for parameter {parameter!r}: {exc}") from exc

print(json.dumps({"status": "ok", "spec_count": len(specs), "processed": processed, "use_mock_source": use_mock}))
